version: '3.8'

services:
  aisya-landing:
    image: ${DOCKER_USERNAME}/aisya-landing:latest
    container_name: aisya-landing
    restart: always
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
    networks:
      - aisya-network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  aisya-network:
    driver: bridge
